### PR TITLE
Add Reaper service and dashboard. Fixes #8

### LINKED ISSUE #8: Add a cassandra-reaper dashboard

### PR DESCRIPTION
**Pull request by rzvoncek**
With this change, the `./gradlew preview` will spin up the entire environment, now including a Reaper instance that automatically registers the cluster and starts a repair.

After a while, the dashboard will look like this:
Screenshot 2020-04-27 at 19 53 39

It's not as fancy as the one I've described [in Reaper's docs](http://cassandra-reaper.io/docs/metrics/dashboards/) because Grafonnet doesn't let me declare all the non-trivial things like gauges(!) and panel-specific time ranges. So this one will have to do for now.

@arodrime , I somehow ended up deleting the two archives and I can't make them go back. Could you please fix that, or tell me how to generate them anew?

### CODE REVIEW

**Comment by arodrime** [comment]
>@arodrime , I somehow ended up deleting the two archives and I can't make them go back. Could you please fix that, or tell me how to generate them anew?

I can do. Taking it from here. FTR, `./gradlew assemble` generates zip files with JSON dashboards.

**Comment by arodrime** [comment]
Had the same trouble using Gauges Radovan, sorry for slowness of the review here, I'll get back to it soon.

**Comment by adejanovski** [comment]
Merged during sprint recap

**Comment by arodrime** [comment]
👍. I could not have the gauge working either.  Anyway good enough for a V1.

**Pull request merged**
